// Copyright 2020 Devlikamov Vladislav

#ifndef MODULES_SEGMENT_TREE_INCLUDE_SEGMENT_TREE_H_
#define MODULES_SEGMENT_TREE_INCLUDE_SEGMENT_TREE_H_

#endif  // MODULES_SEGMENT_TREE_INCLUDE_SEGMENT_TREE_H_
